{"name": "getReturns Maneja Excepción de yfinance.Ticker().history()", "status": "passed", "description": "Verifica cómo responde la vista si la llamada a yfinance.history() falla.", "steps": [{"name": "POST a /getReturns esperando una excepción de yfinance", "status": "passed", "start": 1747074867982, "stop": 1747074867993}, {"name": "Verificar que analyze_data no fue llamado si yfinance falló", "status": "passed", "start": 1747074867993, "stop": 1747074867993}], "attachments": [{"name": "log", "source": "0723e697-c4c6-4aee-a034-de6ed5bde643-attachment.txt", "type": "text/plain"}], "start": 1747074867981, "stop": 1747074867993, "uuid": "28443077-05ae-4b00-8d32-782494387d82", "historyId": "866e7681d7cf183faf2a084b0b470fa1", "testCaseId": "866e7681d7cf183faf2a084b0b470fa1", "fullName": "financialSearch.tests.TestGetReturnsView#test_get_returns_handles_yfinance_exception", "labels": [{"name": "tag", "value": "error_handling"}, {"name": "tag", "value": "returns"}, {"name": "tag", "value": "negative"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Obtención de Datos Financieros (getReturns)"}, {"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "financialSearch"}, {"name": "suite", "value": "tests"}, {"name": "subSuite", "value": "TestGetReturnsView"}, {"name": "host", "value": "nickell01"}, {"name": "thread", "value": "12784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "financialSearch.tests"}]}